# Generated by Django 5.2.7 on 2025-11-05 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_blog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newspage',
            options={'verbose_name': 'News Page', 'verbose_name_plural': 'News Pages'},
        ),
    ]
