# Generated by Django 5.2.7 on 2025-11-05 08:26

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_homepage_blocks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='blocks',
            field=wagtail.fields.StreamField([('text_block', 2), ('image_block', 5), ('custom_image_block', 10)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 100, 'required': True}), 1: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('text', 1)]], {}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 4: ('wagtail.blocks.CharBlock', (), {'max_length': 250, 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 3), ('caption', 4)]], {}), 6: ('wagtail.blocks.CharBlock', (), {'help_text': 'Title', 'max_length': 100, 'required': True}), 7: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Content', 'required': False}), 8: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Image', 'required': True}), 9: ('wagtail.blocks.StructBlock', [[('title', 6), ('text', 7), ('image', 8)]], {'required': True}), 10: ('wagtail.blocks.StructBlock', [[('custom_image', 9)]], {})}),
        ),
    ]
