# Generated by Django 5.2.7 on 2025-11-04 07:40

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
