# Generated by Django 5.2.7 on 2025-11-04 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_alter_blog_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
