# Generated by Django 5.2.7 on 2025-11-05 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainmenu',
            name='menu_type',
            field=models.CharField(choices=[('header', 'Header'), ('footer', 'Footer')], default='header', help_text='Header / Footer', max_length=20),
        ),
    ]
