# Generated by Django 5.2.7 on 2025-11-05 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_menu', '0002_mainmenu_menu_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='slug',
            field=models.SlugField(blank=True, help_text='Slug', max_length=255),
        ),
    ]
